#!/usr/bin/env python3
"""Write a Cloudflare Pages _redirects file sending the reference manual's old root-level links to /doc/.

The manual was the whole of adctoolbox.tokenzhang.com until the illustrations took the root, so anything that ever
linked to /quickstart.html or /api/... has to keep working. One rule per entry at the top of the built manual, which
is a dozen lines and stays right if the manual grows a section.
"""
import sys
from pathlib import Path

dist = Path(sys.argv[1])
doc = dist / "doc"
lines = ["# generated by .github/doc-redirects.py: the manual moved from / to /doc/"]
for entry in sorted(doc.iterdir()):
    # the manual's own front page would shadow the site's, and dotfiles are not served
    if entry.name in {"index.html"} or entry.name.startswith("."):
        continue
    if entry.is_dir():
        lines.append(f"/{entry.name}/* /doc/{entry.name}/:splat 301")
    else:
        lines.append(f"/{entry.name} /doc/{entry.name} 301")
(dist / "_redirects").write_text("\n".join(lines) + "\n")
print("\n".join(lines))
